# Generated by Django 4.2.7 on 2024-01-03 00:53

import CypartaGraphqlSubscriptionsTools.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(default=15)),
            ],
            bases=(CypartaGraphqlSubscriptionsTools.mixins.CypartaSubscriptionModelMixin, models.Model),
        ),
    ]
